kind = "web"
previewPath = "/"
title = "Steakz"
version = "1.0.0"
id = "artifacts/steakz"
router = "path"

[[integratedSkills]]
name = "react-vite"
version = "1.0.0"

[[services]]
name = "web"
paths = [ "/" ]
localPort = 19668

[services.development]
run = "pnpm --filter @workspace/steakz run dev"

[services.production]
build = [ "pnpm", "--filter", "@workspace/steakz", "run", "build" ]
publicDir = "artifacts/steakz/dist/public"
serve = "static"

[[services.production.rewrites]]
from = "/*"
to = "/index.html"

[services.env]
PORT = "19668"
BASE_PATH = "/"
